# Requires the job-dsl plugin
jobs:
  - script: >
      pipelineJob("Hello world") {
        description("Does it work?")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/otterstedt/otternet.ci.git")
                }
                branch("master")
              }
            }
            scriptPath("jenkins/jobs/examples/hello-world/Jenkinsfile")
          }
        }
        disabled(false)
      }
  - script: >
      pipelineJob("Hello world 2") {
        description("Does it work? Maybe?")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/otterstedt/otternet.ci.git")
                }
                branch("master")
              }
            }
            scriptPath("jenkins/jobs/examples/hello-world/Jenkinsfile")
          }
        }
        disabled(false)
      }
  - script: >
      pipelineJob("Node version") {
        description("Show docker agent node version")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/otterstedt/otternet.ci.git")
                }
                branch("master")
              }
            }
            scriptPath("jenkins/jobs/examples/docker-agent/Jenkinsfile")
          }
        }
        disabled(false)
      }
  - script: >
      pipelineJob("Use docker-plugin as agent") {
        description("Does something")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/otterstedt/otternet.ci.git")
                }
                branch("master")
              }
            }
            scriptPath("jenkins/jobs/examples/docker-plugin/Jenkinsfile")
          }
        }
        disabled(false)
      }
jenkins:
  clouds:
    - docker:
        name: "docker-plugin"
        dockerApi:
          dockerHost:
            uri: "unix://var/run/docker.sock"
        templates:
          - labelString: "docker-plugin"
            connector:
              attach:
                user: "jenkins"
            remoteFs: "/home/jenkins/agent"
            instanceCapStr: "10"
            mode: "EXCLUSIVE"
            retentionStrategy:
              idleMinutes: "10"
            dockerTemplateBase:
              image: "jenkins/ssh-agent:latest"
              privileged: true
            removeVolumes: true
