jobs:
  - script: >
      pipelineJob("Hello world 2") {
        description("Does it work? Maybe?")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/otterstedt/otternet.ci.git")
                }
                branch("master")
              }
            }
            scriptPath("jenkins/jobs/examples/hello-world/Jenkinsfile")
          }
        }
        disabled(false)
      }
